### ISSUE TITLE
Weather icons missing, only temperature shown

### ISSUE THREAD

**Issue by membersound** [pveierland/aix-weather-widget#13]
![Screenshot_20191204_163833](https://user-images.githubusercontent.com/5269630/70157122-4aea9280-16b5-11ea-877b-cefb22a11eec.jpg)

What can I do when only temperature is shown?
Android 9. It happened suddenly, and your app worked before for many months.

Tested on two devices Huawei p10.

**Comment by Dudule90** [comment]
Same issue for me

**Comment by rivonia** [comment]
Could try an alternative instead... see https://github.com/pveierland/aix-weather-widget/issues/11#issuecomment-504692649

**Comment by sthen** [comment]
Met.no have made some changes to their API recently, not sure exactly what will have affected the aix widget but it's almost certainly due to this. https://api.met.no/weatherapi/locationforecast/1.9/documentation#New_model_backend%3A_2019-12-03

**Comment by membersound** [comment]
The `LocationforecastLTS` will be terminated in Feb 2020 anyways. So let's hope for the developer to upgrade the external api soon.

**Comment by pveierland** [comment]
Hi! The comment from @sthen points out the issue. An update has now been published to Google Play which fixes the issue (version 0.1.9.20). There is currently an issue with Google Play, so I've only been able to update the free app, and the donation version will be updated as soon as possible.

@membersound The app should only be using the `Locationforecast` API, so the termination of the `LocationforecastLTS` API should not affect the app.
