### ISSUE TITLE
Upgrade of MET Norway Weather API to v.2.0

### ISSUE THREAD

**Issue by jacekfabirkiewicz** [pveierland/aix-weather-widget#20]
As of March 1st, 2021, the old versions of Locationforecast (1.9), Nowcast (0.9) and Weathericon (1.1) are terminated.

[Termination of various products](https://api.met.no/blog/2021-02-04-extremeswwc)

**Comment by membersound** [comment]
Would be great if you could fix that. The widget is not working anymore, probably due to that...

**Comment by jacekfabirkiewicz** [comment]
You may use this fixed version for regions where Norwegian weather data is used: [app-debug.zip](https://github.com/pveierland/aix-weather-widget/files/6097647/app-debug.zip)

**Comment by runewa** [comment]
Just tried this on a Samsung s10e running Android 11 with a "Problem loading widget" error message.

**Comment by jacekfabirkiewicz** [comment]
That's right - this fix works only for lower versions of Android.

@runewa, Android 11 issue is already maintained by Gitsaibot in his fork - I already asked him to merge my fix. Hope he will be able to merge it and provide working app for Android11 soon.

**Comment by safrye** [comment]
Hi,
The fixed version is working fine for me on Android 10. Tusen takk. :) :+1:

**Comment by LaurentSGL** [comment]
Wahoo !!! Thanks a lot for this fix !!!works on redmi Android 10.
Merci

**Comment by buddelflink** [comment]
Fix not working on my Huawei P30 pro (Android 10, EMUI 11, Nova launcher)
