### ISSUE TITLE
Daylight visualization broken

### ISSUE THREAD

**Issue by novoid** [pveierland/aix-weather-widget#8]
Hi!

Since today, I face an issue with the visualization of the day/night:

![2019-03-18T07 19 33 AIX Weather widget daylight visualization issue -- screenshots android](https://user-images.githubusercontent.com/727493/54536955-f8840d00-4991-11e9-9728-38e2662e6cd2.jpg)

![2019-03-18T10 02 22 AIX Weather widget daylight visualization issue -- screenshots android](https://user-images.githubusercontent.com/727493/54536956-f8840d00-4991-11e9-921d-a096ae401b1c.jpg)

![2019-03-18T15 18 43 AIX Weather widget daylight visualization issue -- screenshots android](https://user-images.githubusercontent.com/727493/54536957-f8840d00-4991-11e9-94f8-547b40f474fc.jpg)

I already did re-draw the widget by selecting a different location and switching back. This did not resolve the issue.

One Plus 5, OxygenOS 9.0.4 (latest), Android 9 (from Jan 1st 2019)

**Comment by drmrbrewer** [comment]
You're the lucky one; mine fails to get any weather data at all.

**Comment by rivonia** [comment]
For me:

![Screenshot_20190318-185200](https://user-images.githubusercontent.com/29942149/54555711-275cac00-49af-11e9-8c3b-ec1627b7b109.jpg)

**Comment by AlainMuller** [comment]
Same thing for me but it's not a display issue, it seems to be relative to the servers : if you go to the Update Settings and data source, if you check anything else than Auto the sync will fail (I'm in France and cannot access NOAA WS)... 😥

**Comment by novoid** [comment]
Hi!
My issue got resolved with update to 0.1.9.18 just now :-)
That was fast.

**Comment by AlainMuller** [comment]
Wow, indeed, amazing reactivity @pveierland ! 😎 
Thank you for this amazing app BTW!
