### ISSUE TITLE
Failed to get weather data...

### ISSUE THREAD

**Issue by sddakoty** [pveierland/aix-weather-widget#9]
Weather data cannot be fetched since the last 24h.
v32.

Also several comments in playstore hint at this problem.

**Comment by AlainMuller** [comment]
See the previous issue : #8 
It's already been solved in version `0.1.9.18`, just update you app 😉

**Comment by sddakoty** [comment]
I tried the `0.1.9.18-32` but the issue still remains.

**Comment by pveierland** [comment]
An updated version (0.1.9.19-33) has been posted to Google Play which should fix this issue. Please remove your current widgets and clear the application data if you are having any issues.

**Comment by wcbdata** [comment]
Looks like 0.1.9.20 may be having this problem with NWS data again. NMI data seems to be loading fine. NWS data seems to have ended a couple of days ago. Started with a temperature line that just ended midway across the widget, and has been failing to load ever since.
